### ISSUE TITLE
Account signup page throws HTTP 500 error

### ISSUE THREAD

**Issue by dreshfield** [michaelkirkpatrick/catalog-beer#10]
Attempted to create an account to start making API calls for a time-sensitive academic project, but the signup page is missing a submit button.

Checking the console in Safari and Chrome showed the `GET` request to https://catalog.beer/signup returns a 500 error, as well as the following: `Unchecked runtime.lastError: The message port closed before a response was received.`

**Comment by michaelkirkpatrick** [comment]
Thank you Dresh! I'm sorry you weren't able to get signed up in time to use Catalog.beer for your academic project. The bug has been fixed. You should no longer see a 500 error when you go to the signup page.
